controller:
  image:
    registry: docker.io
    repository: jenkins/jenkins
    tag: jdk21
    pullPolicy: Always

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - docker-workflow

  containerEnv:
    - name: DOCKER_HOST
      value: unix:///var/run/docker.sock

  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock

  volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock

  initContainers:
    - name: install-docker-cli
      image: docker:24
      command:
        - sh
        - -c
        - |
          cp /usr/local/bin/docker /usr/local/bin/docker