replicaCount: 1

image:
  repository: lazyguyshit/le-se-de
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 18080

ingress:
  enabled: true
  className: nginx
  host: app.local
  path: /
  pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

app:
  version: "latest"
